<form class="flex-col flex-middle register-form" action="/router.php?path=register">
  <h2>Register your account here !</h2>
  <label>Username</label>
  <input type="text" name="username" placeholder="username"/>
  <label>Email address</label>
  <input type="text" name="email" placeholder="email"/>
  <label>Password</label>
  <input type="password" name="pwd" placeholder="password"/>
  <input type="password" name="pwd-confirm" placeholder="confirm password"/>
  <input type="submit" value="Confirm"/>
</form>
