<!DOCTYPE html>
<html lang="en">

  <!-- HEAD -->
  <head>
    <title>Grand Conquest</title>
    <link rel="icon" type="image/png" href="/favicon.png"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich"/>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css"/>
    <script type="application/javascript" src="/static/js/main.js"></script>
  </head>

  <!-- BODY -->
  <body class="flex-col">

    <div id="flash-wrapper"></div>

    <header class="flex-col flex-middle">
      <div class="flex-col flex-middle header-screen">
        <h1><a href="/">Grand Conquest</a></h1>
        <div class="flex-row flex-middle">
          <?php if (isset($_SESSION) && count($_SESSION) > 0) {
            include_once(dirname(__FILE__).'/header/logged_in.phtml');
          } else {
            include_once(dirname(__FILE__).'/header/logged_out.phtml');
          } ?>
        </div>
      </div>
    </header>

    <main class="flex-col">
      <?php include_once(PAGEVIEW); ?>
    </main>

    <footer>
      <p>Backend V-<?php echo(GC_VERSION); ?></p>
    </footer>
  </body>
</html>
