<!DOCTYPE html>
<html lang="en">

  <!-- HEAD -->
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"/>

    <meta property="og:title" content="Grand Conquest"/>
    <meta property="og:description" content="Grand Conquest is an online multiplayer wargame. No paywalls, no bullshit."/>
    <meta property="og:url" content="<?php echo("https://{$_SERVER['SERVER_NAME']}{$_SERVER['REQUEST_URI']}") ?>"/>
    <meta property="og:image" content="https://grand-conquest.com/favicon.png"/>
    <meta property="og:type" content="website"/>

    <title>Grand Conquest</title>
    <link rel="icon" type="image/png" href="/favicon.png"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich"/>
    <link rel="stylesheet" type="text/css" href="/static/css/main.css"/>
    <script type="application/javascript" src="/static/js/main.js"></script>
  </head>

  <!-- BODY -->
  <body class="flex-col">

    <div id="flash-wrapper"></div>

    <header class="flex-col flex-middle">
      <div class="flex-col flex-middle header-screen">
        <h1><a href="/">Grand Conquest</a></h1>
        <div class="flex-row flex-middle">
          <?php if (isset($_SESSION) && count($_SESSION) > 0) {
            include_once(dirname(__FILE__).'/header/logged_in.phtml');
          } else {
            include_once(dirname(__FILE__).'/header/logged_out.phtml');
          } ?>
        </div>
      </div>
    </header>

    <main class="flex-col">
      <?php include_once(PAGEVIEW); ?>
    </main>

    <footer>
      <p>Backend V-<?php echo(GC_VERSION); ?></p>
    </footer>
  </body>
</html>
